CREATE TABLE "caregiver" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"full_name" text NOT NULL,
	"photos" text[] DEFAULT '{}' NOT NULL,
	"address" jsonb NOT NULL,
	"geocode" jsonb NOT NULL,
	"services" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"about_title" text NOT NULL,
	"about_description" text NOT NULL,
	"skills" text[] DEFAULT '{}' NOT NULL,
	"availability" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"unavailable_days" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"pet_type_preference" text[] DEFAULT '{}' NOT NULL,
	"dog_size" text[] DEFAULT '{}' NOT NULL,
	"dog_age" text[] DEFAULT '{}' NOT NULL,
	"certifications" text[] DEFAULT '{}' NOT NULL,
	"languages" text[] DEFAULT '{}' NOT NULL,
	"mobility" text[] DEFAULT '{}' NOT NULL,
	"average_rating" real DEFAULT 0 NOT NULL,
	"total_reviews" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp
);
